// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: api/v1/talos.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AttestRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ServiceAccountToken string                 `protobuf:"bytes,1,opt,name=service_account_token,json=serviceAccountToken,proto3" json:"service_account_token,omitempty"` // The K8s JWT
	WorkloadName        string                 `protobuf:"bytes,2,opt,name=workload_name,json=workloadName,proto3" json:"workload_name,omitempty"`
	Namespace           string                 `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *AttestRequest) Reset() {
	*x = AttestRequest{}
	mi := &file_api_v1_talos_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttestRequest) ProtoMessage() {}

func (x *AttestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_talos_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttestRequest.ProtoReflect.Descriptor instead.
func (*AttestRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_talos_proto_rawDescGZIP(), []int{0}
}

func (x *AttestRequest) GetServiceAccountToken() string {
	if x != nil {
		return x.ServiceAccountToken
	}
	return ""
}

func (x *AttestRequest) GetWorkloadName() string {
	if x != nil {
		return x.WorkloadName
	}
	return ""
}

func (x *AttestRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type AttestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Certificate   []byte                 `protobuf:"bytes,1,opt,name=certificate,proto3" json:"certificate,omitempty"`                 // PEM encoded X.509
	PrivateKey    []byte                 `protobuf:"bytes,2,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"` // PEM encoded Private Key (Generated locally ideally, but for simplicity here)
	CaBundle      []byte                 `protobuf:"bytes,3,opt,name=ca_bundle,json=caBundle,proto3" json:"ca_bundle,omitempty"`       // PEM encoded CA Chain
	SpiffeId      string                 `protobuf:"bytes,4,opt,name=spiffe_id,json=spiffeId,proto3" json:"spiffe_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttestResponse) Reset() {
	*x = AttestResponse{}
	mi := &file_api_v1_talos_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttestResponse) ProtoMessage() {}

func (x *AttestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_talos_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttestResponse.ProtoReflect.Descriptor instead.
func (*AttestResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_talos_proto_rawDescGZIP(), []int{1}
}

func (x *AttestResponse) GetCertificate() []byte {
	if x != nil {
		return x.Certificate
	}
	return nil
}

func (x *AttestResponse) GetPrivateKey() []byte {
	if x != nil {
		return x.PrivateKey
	}
	return nil
}

func (x *AttestResponse) GetCaBundle() []byte {
	if x != nil {
		return x.CaBundle
	}
	return nil
}

func (x *AttestResponse) GetSpiffeId() string {
	if x != nil {
		return x.SpiffeId
	}
	return ""
}

type CheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subject       string                 `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"` // The SPIFFE ID of the workload
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`   // e.g., "exec", "net-outbound"
	Target        string                 `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"`   // e.g., "/bin/rm", "api.openai.com"
	Context       map[string]string      `protobuf:"bytes,4,rep,name=context,proto3" json:"context,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckRequest) Reset() {
	*x = CheckRequest{}
	mi := &file_api_v1_talos_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRequest) ProtoMessage() {}

func (x *CheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_talos_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRequest.ProtoReflect.Descriptor instead.
func (*CheckRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_talos_proto_rawDescGZIP(), []int{2}
}

func (x *CheckRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *CheckRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *CheckRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *CheckRequest) GetContext() map[string]string {
	if x != nil {
		return x.Context
	}
	return nil
}

type CheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Allowed       bool                   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckResponse) Reset() {
	*x = CheckResponse{}
	mi := &file_api_v1_talos_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckResponse) ProtoMessage() {}

func (x *CheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_talos_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckResponse.ProtoReflect.Descriptor instead.
func (*CheckResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_talos_proto_rawDescGZIP(), []int{3}
}

func (x *CheckResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *CheckResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_api_v1_talos_proto protoreflect.FileDescriptor

const file_api_v1_talos_proto_rawDesc = "" +
	"\n" +
	"\x12api/v1/talos.proto\x12\x02v1\"\x86\x01\n" +
	"\rAttestRequest\x122\n" +
	"\x15service_account_token\x18\x01 \x01(\tR\x13serviceAccountToken\x12#\n" +
	"\rworkload_name\x18\x02 \x01(\tR\fworkloadName\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\"\x8d\x01\n" +
	"\x0eAttestResponse\x12 \n" +
	"\vcertificate\x18\x01 \x01(\fR\vcertificate\x12\x1f\n" +
	"\vprivate_key\x18\x02 \x01(\fR\n" +
	"privateKey\x12\x1b\n" +
	"\tca_bundle\x18\x03 \x01(\fR\bcaBundle\x12\x1b\n" +
	"\tspiffe_id\x18\x04 \x01(\tR\bspiffeId\"\xcd\x01\n" +
	"\fCheckRequest\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12\x16\n" +
	"\x06target\x18\x03 \x01(\tR\x06target\x127\n" +
	"\acontext\x18\x04 \x03(\v2\x1d.v1.CheckRequest.ContextEntryR\acontext\x1a:\n" +
	"\fContextEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"A\n" +
	"\rCheckResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason2B\n" +
	"\x0fIdentityService\x12/\n" +
	"\x06Attest\x12\x11.v1.AttestRequest\x1a\x12.v1.AttestResponse2=\n" +
	"\rPolicyService\x12,\n" +
	"\x05Check\x12\x10.v1.CheckRequest\x1a\x11.v1.CheckResponseB'Z%github.com/yourorg/talos-vault/api/v1b\x06proto3"

var (
	file_api_v1_talos_proto_rawDescOnce sync.Once
	file_api_v1_talos_proto_rawDescData []byte
)

func file_api_v1_talos_proto_rawDescGZIP() []byte {
	file_api_v1_talos_proto_rawDescOnce.Do(func() {
		file_api_v1_talos_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_talos_proto_rawDesc), len(file_api_v1_talos_proto_rawDesc)))
	})
	return file_api_v1_talos_proto_rawDescData
}

var file_api_v1_talos_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_v1_talos_proto_goTypes = []any{
	(*AttestRequest)(nil),  // 0: v1.AttestRequest
	(*AttestResponse)(nil), // 1: v1.AttestResponse
	(*CheckRequest)(nil),   // 2: v1.CheckRequest
	(*CheckResponse)(nil),  // 3: v1.CheckResponse
	nil,                    // 4: v1.CheckRequest.ContextEntry
}
var file_api_v1_talos_proto_depIdxs = []int32{
	4, // 0: v1.CheckRequest.context:type_name -> v1.CheckRequest.ContextEntry
	0, // 1: v1.IdentityService.Attest:input_type -> v1.AttestRequest
	2, // 2: v1.PolicyService.Check:input_type -> v1.CheckRequest
	1, // 3: v1.IdentityService.Attest:output_type -> v1.AttestResponse
	3, // 4: v1.PolicyService.Check:output_type -> v1.CheckResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_v1_talos_proto_init() }
func file_api_v1_talos_proto_init() {
	if File_api_v1_talos_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_talos_proto_rawDesc), len(file_api_v1_talos_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_api_v1_talos_proto_goTypes,
		DependencyIndexes: file_api_v1_talos_proto_depIdxs,
		MessageInfos:      file_api_v1_talos_proto_msgTypes,
	}.Build()
	File_api_v1_talos_proto = out.File
	file_api_v1_talos_proto_goTypes = nil
	file_api_v1_talos_proto_depIdxs = nil
}
